### ISSUE TITLE
[GEN2] Implement Drift's Isolate API

### ISSUE THREAD

**Issue by V3ntus** [V3ntus/darvester#93]
https://drift.simonbinder.eu/docs/advanced-features/isolates/

The code works on the main isolate and will display Guilds and Users. When spawning a harvester isolate, the code will throw the exception above.

This is the believed cause of this error:
```
[ERROR:flutter/runtime/dart_isolate.cc(1098)] Unhandled exception:
Bad state: The BackgroundIsolateBinaryMessenger.instance value is invalid until BackgroundIsolateBinaryMessenger.ensureInitialized is executed.
#0      BackgroundIsolateBinaryMessenger.instance (package:flutter/src/services/_background_isolate_binary_messenger_io.dart:27:7)
#1      _findBinaryMessenger (package:flutter/src/services/platform_channel.dart:135:42)
#2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:273:56)
#3      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:15)
#4      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:491:12)
#5      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:518:49)
#6      MethodChannelSharedPreferencesStore.getAll (package:shared_preferences_platform_interface/method_channel_shared_preferences.dart:60:28)
#7      SharedPreferences._getSharedPreferencesMap (package:shared_preferences/shared_preferences.dart:229:38)
#8      SharedPreferences.getInstance (package:shared_preferences/shared_preferences.dart:67:19)
#9      Preferences.getString (package:darvester/util.dart:104:63)
#10     _openConnection.<anonymous closure> (package:darvester/database.dart:113:54)
#11     new Future.sync (dart:async/future.dart:302:31)
#12     LazyDatabase._awaitOpened (package:drift/src/utils/lazy_database.dart:47:14)
#13     LazyDatabase.ensureOpen (package:drift/src/utils/lazy_database.dart:61:12)
#14     DatabaseConnectionUser.doWhenOpened (package:drift/src/runtime/api/connection_user.dart:162:21)
#15     CustomSelectStatement._executeRaw (package:drift/src/runtime/query_builder/statements/select/custom_select.dart:51:16)
#16     CustomSelectStatement.get (package:drift/src/runtime/query_builder/statements/select/custom_select.dart:37:12)
#17     Selectable.getSingle (package:drift/src/runtime/query_builder/statements/query.dart:230:19)
#18     DarvesterDatabase.getTableCount (package:darvester/database.dart:91:82)
#19     DarvesterDatabase.upsertGuild (package:darvester/database.dart:103:16)
#20     Harvester.loop (package:darvester/darvester/core.dart:169:10)
<asynchronous suspension>
```

**Comment by V3ntus** [comment]
#92

**Comment by V3ntus** [comment]
<details>
<summary>main.dart</summary>

```dart
void main() {
    runApp(Provider<MyDatabase>(
    create: (BuildContext context) => MyDatabase(DatabaseConnection.delayed(
      Future.sync(() async {
        final DriftIsolate isolate = await createDriftIsolate();
        return isolate.connect();
      }),
    )),
    child: const MyApp(),
    dispose: (BuildContext context, MyDatabase db) => db.close(),
  ));
}
```

</details>

<details>
<summary>database.dart</summary>

```dart
@DriftDatabase(tables: [Guilds, Users])
class MyDatabase extends _$MyDatabase {
  MyDatabase([QueryExecutor? executor]) : super(executor ?? _openConnection());

  @override
  int get schemaVersion => 1;
  ...
}

Future<DriftIsolate> createDriftIsolate() async {
  final RootIsolateToken token = RootIsolateToken.instance!;
  return await DriftIsolate.spawn(() {
    BackgroundIsolateBinaryMessenger.ensureInitialized(token);

    logger.info("Giving isolate a DriftIsolate database connector");
    return _openConnection();
  });
}

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final File file;
    String databasePath = await Preferences.instance.getString("databasePath");
    if (databasePath.isEmpty) {
      final dbFolder = await getApplicationSupportDirectory();
      file = File(p.join(dbFolder.path, 'harvested.db'));
    } else {
      file = File(databasePath);
    }
    logger.info("LazyDatabase is opening database file: ${file.absolute.path}");
    return NativeDatabase(file);
  });
}
```

</details>

<details>
<summary>my_isolate.dart</summary>

```dart
void _spawnMyIsolate(List<MyDatabase> args) {
    MyDatabase db = args[0];
    // do work
    db.upsertRow(row);
}

MyDatabase db = MyDatabase(
  DatabaseConnection.delayed(Future.sync(() async {
    final isolate = await createDriftIsolate();
    return isolate.connect();
  }))
);
myIsolate = await Isolate.spawn(_spawnMyIsolate, [db]);
```

</details>

---  

The code will appear to run without error, besides the debug warning from drift:
```
flutter: WARNING (drift): It looks like you've created the database class DarvesterDatabase multiple times. When these two databases use the same QueryExecutor, race conditions will occur and might corrupt the database. 
flutter: Try to follow the advice at https://drift.simonbinder.eu/faq/#using-the-database or, if you know what you're doing, set driftRuntimeOptions.dontWarnAboutMultipleDatabases = true
flutter: Here is the stacktrace from when the database was opened a second time:
flutter: #0      GeneratedDatabase._handleInstantiated (package:drift/src/runtime/api/db_base.dart:89:30)
flutter: #1      new GeneratedDatabase (package:drift/src/runtime/api/db_base.dart:61:12)
flutter: #2      new _$MyDatabase (package:darvester/database.g.dart:1152:42)
flutter: #3      new MyDatabase (package:darvester/database.dart:60:50)
flutter: #4      MyIsolate._init (package:darvester/darvester/harvester_isolate.dart:53:28)
flutter: #5      new MyIsolate (package:darvester/darvester/harvester_isolate.dart:48:5)
flutter: #6      _ManagerState.spawnHarvesterThread (package:darvester/routes/IsolateManager.dart:40:35)
flutter: #7      _ManagerState.build.<anonymous closure> (package:darvester/routes/IsolateManager.dart:92:59)
flutter: #8      EditableTextState._finalizeEditing (package:flutter/src/widgets/editable_text.dart:2773:18)
flutter: #9      EditableTextState.performAction (package:flutter/src/widgets/editable_text.dart:2618:9)
flutter: #10     TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1870:37)
flutter: #11     TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1753:20)
flutter: #12     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:555:55)
flutter: #13     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:548:34)
flutter: #14     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:393:35)
flutter: #15     _invoke2 (dart:ui/hooks.dart:183:13)
flutter: #16     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)
flutter: #17     _Channel.push (dart:ui/channel_buffers.dart:130:31)
flutter: #18     ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)
flutter: #19     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:664:22)
flutter: #20     _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)
flutter: This warning will only appear on debug builds.
```

Custom log messages from `MyDatabase` upsert methods will output without error, but upon viewing the database, there are no new rows (working on a fresh, empty database).

I will do more troubleshooting on my `upsertRow` method to rule out if this is a query issue. The method in question is:
```dart
Future<int> upsertGuild(DBGuild guild) async {
  logger.debug("Upserting guild: ${guild.id}");
  if ((await getTableCount("guilds", searchTerm: guild.id)) <= 0) {
    guild = guild.copyWith(firstSeen: Value(DateTime.now()));
  }
  return into(guilds).insertOnConflictUpdate(guild);
}
```

**Comment by V3ntus** [comment]
1fd12f644f95fb95438ae71b0ad787306f4eb1a1

WIP implementation

**Comment by V3ntus** [comment]
Tracking https://github.com/simolus3/drift/discussions/2366

**Comment by V3ntus** [comment]
Working refactor in 9c75290

A singleton needs to be implemented for the main isolate still. Currently in this commit, routes are creating more than one instance of `DarvesterDatabase`. Not good

**Comment by V3ntus** [comment]
Done 584caeab85ffa293f99cec6cff500ebcba132c01
